# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Howto < Formula
  desc "A humble command-line assistant"
  homepage "https://github.com/nalgeon/howto"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nalgeon/howto/releases/download/0.2.0/howto_0.2.0_darwin_amd64.tar.gz"
      sha256 "db49d7b789733392327d46969bfcf790d550fd49dbc010a71c7e669397f6f105"

      def install
        bin.install "howto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nalgeon/howto/releases/download/0.2.0/howto_0.2.0_darwin_arm64.tar.gz"
      sha256 "777e97749a8c684645dd8192c0d23adbaac1dc3bcfd2820b25ad4d7e6f8c530e"

      def install
        bin.install "howto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nalgeon/howto/releases/download/0.2.0/howto_0.2.0_linux_amd64.tar.gz"
        sha256 "3f49f3090c45b463a2d80476d945806440ffe487af6fa04704ec9de31a40b2a3"

        def install
          bin.install "howto"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nalgeon/howto/releases/download/0.2.0/howto_0.2.0_linux_arm64.tar.gz"
        sha256 "ae951dc1bead12588ae5667173bdec529fea48274c89b91394b13663a6b896c5"

        def install
          bin.install "howto"
        end
      end
    end
  end
end
