# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Howto < Formula
  desc "A humble command-line assistant"
  homepage "https://github.com/nalgeon/howto"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nalgeon/howto/releases/download/v0.1.1/howto_0.1.1_darwin_amd64.tar.gz"
      sha256 "a8501d6c58ff10347e7e1ffb15d1cef6cef70bff6ec053e1f1bf10a27e527a3f"

      def install
        bin.install "howto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nalgeon/howto/releases/download/v0.1.1/howto_0.1.1_darwin_arm64.tar.gz"
      sha256 "bc5cab07bd1c6f60c343ba2f99083b19a0f9b9820f8e445c623056c2eef0a9cb"

      def install
        bin.install "howto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nalgeon/howto/releases/download/v0.1.1/howto_0.1.1_linux_amd64.tar.gz"
        sha256 "234b476756261dfa9bc87e222fba76d65f5ed61e42cf299fcb366a6ce317ad08"

        def install
          bin.install "howto"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nalgeon/howto/releases/download/v0.1.1/howto_0.1.1_linux_arm64.tar.gz"
        sha256 "19a05cd4c33cc60169218f7da77c4d2cc58d546343cff09722d6acc6e39d9f46"

        def install
          bin.install "howto"
        end
      end
    end
  end
end
