name: publish

on:
    push:
        tags:
            - "v*.*.*"

permissions:
    contents: write

jobs:
    publish:
        name: Release and publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version-file: "go.mod"

            - name: Install dependencies
              run: go get .

            - name: Release and publish
              uses: goreleaser/goreleaser-action@v6
              with:
                  args: release --clean
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
